# -*- coding: utf-8 -*-
"""
Date de creation : 14 octobre 2025
Auteurs: Marie Louise MILLIEN & Elouen WURMSER
Projet: TP4 - CasseBrique
Titre: Fichier des constantes
"""

#CONSTANTES DES BRIQUES
VIES = 2
COULEUR = "green"
TYPE = "normal"
LIGNES = 5
COLONNES = 9
LARGEUR_BRIQUE = 100
HAUTEUR_BRIQUE = 25
TOP_OFFSET = 30
PADDING = 6

#CONSTANTES DE LA BALLE
RAYON_BALLE = 8
VITESSE_BALLE = 5.0   # pixels par frame (ajustable)
FACTOR = 1.05

#CONSTANTES DU CANVAS
LARGEUR_CANVA = 900
HAUTEUR_CANVA = 500

#CONSTANTES DE LA RAQUETTE
VITESSE_RAQUETTE = 100
LARGEUR_RAQUETTE = 160
HAUTEUR_RAQUETTE = 16

#CONSTANTES POUR LE JEU GENERAL
FPS_DELAY_MS = 16   # ~60 FPS
NOMBRE_VIES = 3
