# -*- coding: utf-8 -*-
"""
Date de creation : 14 octobre 2025
Auteurs: Marie Louise MILLIEN & Elouen WURMSER
Projet: TP4 - CasseBrique
Titre: Fichier des constantes
"""
# CONSTANTE POUR LA BRIQUES
VIES = 2
COULEUR = "green"
TYPE = "normal"
LIGNES = 10
COLONNES = 9
LARGEUR_BRIQUE = 80
HAUTEUR_BRIQUE = 20
TOP_OFFSET = 30
PADDING = 6

# BALLES
RAYON_BALLE = 8
VITESSE_BALLE = 6.0   # pixels par frame (ajustable)
FACTOR = 1.05

# CANVA
LARGEUR_CANVA = 900
HAUTEUR_CANVA = 600

# RAQUETTE
VITESSE_RAQUETTE = 30
LARGEUR_RAQUETTE = 160
HAUTEUR_RAQUETTE = 16

# AUTRES
FPS_DELAY_MS = 16   # ~60 FPS
NOMBRE_VIES = 4

